name: Professional Resume
favicon: null
layout_spectrum: 0.5738218
typography_spectrum: 0.1097364
title: Cameron T. Belt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8342016
  lightness: 0.7006677
  saturation: 0.02731637
  rhythmicContrast: 0.5118284
purpose: []
